name: organizer
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #shared data
  mobx: ^2.0.4
  flutter_mobx: ^2.0.2
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.2
  #database
  sqflite: ^2.0.0+4

  flutter_slidable: ^0.6.0
  intl: ^0.17.0
  image_picker: ^0.8.4
  flutter_calendar_carousel: ^2.0.3
  animated_text_kit: ^4.2.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/img.png"
  adaptive_icon_foreground: "dev_assets/img.png"

flutter:
  uses-material-design: true

  fonts:
    - family: SquadaOne
      fonts:
      - asset: fonts/SquadaOne-Regular.ttf

